/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as PedirRouteImport } from './routes/pedir'
import { Route as ParceirosRouteImport } from './routes/parceiros'
import { Route as MototaxiRouteImport } from './routes/mototaxi'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as EscolherRouteImport } from './routes/escolher'
import { Route as EntregasRouteImport } from './routes/entregas'
import { Route as CidadeRouteImport } from './routes/cidade'
import { Route as AdministradorRouteImport } from './routes/administrador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmRouteImport } from './routes/adm'
import { Route as AdmGateRouteImport } from './routes/_admGate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PedirIndexRouteImport } from './routes/pedir.index'
import { Route as PassageiroIndexRouteImport } from './routes/passageiro.index'
import { Route as MototaxistaIndexRouteImport } from './routes/mototaxista.index'
import { Route as MercadoIndexRouteImport } from './routes/mercado.index'
import { Route as FoodIndexRouteImport } from './routes/food.index'
import { Route as CidadeIndexRouteImport } from './routes/cidade.index'
import { Route as PedirPerfilRouteImport } from './routes/pedir.perfil'
import { Route as PedirPedidosRouteImport } from './routes/pedir.pedidos'
import { Route as PedirCheckoutRouteImport } from './routes/pedir.checkout'
import { Route as PedirCategoriasRouteImport } from './routes/pedir.categorias'
import { Route as PedirCarrinhoRouteImport } from './routes/pedir.carrinho'
import { Route as PedirBuscarRouteImport } from './routes/pedir.buscar'
import { Route as PassageiroPerfilRouteImport } from './routes/passageiro.perfil'
import { Route as PassageiroHomeRouteImport } from './routes/passageiro.home'
import { Route as PassageiroCorridasRouteImport } from './routes/passageiro.corridas'
import { Route as PassageiroCarteiraRouteImport } from './routes/passageiro.carteira'
import { Route as ParceirosPainelRouteImport } from './routes/parceiros.painel'
import { Route as ParceirosMercadoRouteImport } from './routes/parceiros.mercado'
import { Route as ParceirosCadastroRouteImport } from './routes/parceiros.cadastro'
import { Route as ParceirosAuthRouteImport } from './routes/parceiros.auth'
import { Route as MototaxistaPlanosRouteImport } from './routes/mototaxista.planos'
import { Route as MototaxistaPagamentoRouteImport } from './routes/mototaxista.pagamento'
import { Route as MototaxistaMercadoRouteImport } from './routes/mototaxista.mercado'
import { Route as MototaxistaHomeRouteImport } from './routes/mototaxista.home'
import { Route as MototaxistaFotoRouteImport } from './routes/mototaxista.foto'
import { Route as MototaxistaFoodRouteImport } from './routes/mototaxista.food'
import { Route as MototaxistaDocumentosRouteImport } from './routes/mototaxista.documentos'
import { Route as MototaxistaCadastroRouteImport } from './routes/mototaxista.cadastro'
import { Route as MototaxistaAuthRouteImport } from './routes/mototaxista.auth'
import { Route as MototaxistaAguardandoRouteImport } from './routes/mototaxista.aguardando'
import { Route as MercadoPerfilRouteImport } from './routes/mercado.perfil'
import { Route as MercadoPedidosRouteImport } from './routes/mercado.pedidos'
import { Route as MercadoCheckoutRouteImport } from './routes/mercado.checkout'
import { Route as MercadoCarrinhoRouteImport } from './routes/mercado.carrinho'
import { Route as MercadoBuscarRouteImport } from './routes/mercado.buscar'
import { Route as FoodHomeRouteImport } from './routes/food.home'
import { Route as FoodEsqueciPinRouteImport } from './routes/food.esqueci-pin'
import { Route as FoodCadastroRouteImport } from './routes/food.cadastro'
import { Route as FoodAuthRouteImport } from './routes/food.auth'
import { Route as EstabelecimentoPainelRouteImport } from './routes/estabelecimento.painel'
import { Route as EstabelecimentoMercadoRouteImport } from './routes/estabelecimento.mercado'
import { Route as EmpresaHomeRouteImport } from './routes/empresa.home'
import { Route as EmpresaCadastroRouteImport } from './routes/empresa.cadastro'
import { Route as EmpresaAuthRouteImport } from './routes/empresa.auth'
import { Route as CidadeServicosRouteImport } from './routes/cidade.servicos'
import { Route as CadastroPassageiroRouteImport } from './routes/cadastro.passageiro'
import { Route as AuthPassageiroRouteImport } from './routes/auth.passageiro'
import { Route as AuthMototaxistaRouteImport } from './routes/auth.mototaxista'
import { Route as AppPassageiroRouteImport } from './routes/app.passageiro'
import { Route as AppParceirosRouteImport } from './routes/app.parceiros'
import { Route as AppMototaxiRouteImport } from './routes/app.mototaxi'
import { Route as AppEntregasRouteImport } from './routes/app.entregas'
import { Route as AppAdministradorRouteImport } from './routes/app.administrador'
import { Route as AdmSuspensoRouteImport } from './routes/adm.suspenso'
import { Route as AdmNegadoRouteImport } from './routes/adm.negado'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PedirProdutoIdRouteImport } from './routes/pedir.produto.$id'
import { Route as PedirLojaIdRouteImport } from './routes/pedir.loja.$id'
import { Route as PedirConfirmadoIdRouteImport } from './routes/pedir.confirmado.$id'
import { Route as PedirAcompanharIdRouteImport } from './routes/pedir.acompanhar.$id'
import { Route as MercadoProdutoIdRouteImport } from './routes/mercado.produto.$id'
import { Route as MercadoLojaIdRouteImport } from './routes/mercado.loja.$id'
import { Route as MercadoConfirmadoIdRouteImport } from './routes/mercado.confirmado.$id'
import { Route as MercadoAcompanharIdRouteImport } from './routes/mercado.acompanhar.$id'
import { Route as AdmGateAdmPrecosRouteImport } from './routes/_admGate.adm.precos'
import { Route as AdmGateAdmPainelRouteImport } from './routes/_admGate.adm.painel'
import { Route as AdmGateAdmGestaoRouteImport } from './routes/_admGate.adm.gestao'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirRoute = PedirRouteImport.update({
  id: '/pedir',
  path: '/pedir',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosRoute = ParceirosRouteImport.update({
  id: '/parceiros',
  path: '/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxiRoute = MototaxiRouteImport.update({
  id: '/mototaxi',
  path: '/mototaxi',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const EscolherRoute = EscolherRouteImport.update({
  id: '/escolher',
  path: '/escolher',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregasRoute = EntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadeRoute = CidadeRouteImport.update({
  id: '/cidade',
  path: '/cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministradorRoute = AdministradorRouteImport.update({
  id: '/administrador',
  path: '/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmRoute = AdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmGateRoute = AdmGateRouteImport.update({
  id: '/_admGate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedirIndexRoute = PedirIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PedirRoute,
} as any)
const PassageiroIndexRoute = PassageiroIndexRouteImport.update({
  id: '/passageiro/',
  path: '/passageiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaIndexRoute = MototaxistaIndexRouteImport.update({
  id: '/mototaxista/',
  path: '/mototaxista/',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoIndexRoute = MercadoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MercadoRoute,
} as any)
const FoodIndexRoute = FoodIndexRouteImport.update({
  id: '/food/',
  path: '/food/',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadeIndexRoute = CidadeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CidadeRoute,
} as any)
const PedirPerfilRoute = PedirPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => PedirRoute,
} as any)
const PedirPedidosRoute = PedirPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => PedirRoute,
} as any)
const PedirCheckoutRoute = PedirCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PedirRoute,
} as any)
const PedirCategoriasRoute = PedirCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => PedirRoute,
} as any)
const PedirCarrinhoRoute = PedirCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => PedirRoute,
} as any)
const PedirBuscarRoute = PedirBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => PedirRoute,
} as any)
const PassageiroPerfilRoute = PassageiroPerfilRouteImport.update({
  id: '/passageiro/perfil',
  path: '/passageiro/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroHomeRoute = PassageiroHomeRouteImport.update({
  id: '/passageiro/home',
  path: '/passageiro/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroCorridasRoute = PassageiroCorridasRouteImport.update({
  id: '/passageiro/corridas',
  path: '/passageiro/corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroCarteiraRoute = PassageiroCarteiraRouteImport.update({
  id: '/passageiro/carteira',
  path: '/passageiro/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const ParceirosPainelRoute = ParceirosPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => ParceirosRoute,
} as any)
const ParceirosMercadoRoute = ParceirosMercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => ParceirosRoute,
} as any)
const ParceirosCadastroRoute = ParceirosCadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => ParceirosRoute,
} as any)
const ParceirosAuthRoute = ParceirosAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => ParceirosRoute,
} as any)
const MototaxistaPlanosRoute = MototaxistaPlanosRouteImport.update({
  id: '/mototaxista/planos',
  path: '/mototaxista/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaPagamentoRoute = MototaxistaPagamentoRouteImport.update({
  id: '/mototaxista/pagamento',
  path: '/mototaxista/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaMercadoRoute = MototaxistaMercadoRouteImport.update({
  id: '/mototaxista/mercado',
  path: '/mototaxista/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaHomeRoute = MototaxistaHomeRouteImport.update({
  id: '/mototaxista/home',
  path: '/mototaxista/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaFotoRoute = MototaxistaFotoRouteImport.update({
  id: '/mototaxista/foto',
  path: '/mototaxista/foto',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaFoodRoute = MototaxistaFoodRouteImport.update({
  id: '/mototaxista/food',
  path: '/mototaxista/food',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaDocumentosRoute = MototaxistaDocumentosRouteImport.update({
  id: '/mototaxista/documentos',
  path: '/mototaxista/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaCadastroRoute = MototaxistaCadastroRouteImport.update({
  id: '/mototaxista/cadastro',
  path: '/mototaxista/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaAuthRoute = MototaxistaAuthRouteImport.update({
  id: '/mototaxista/auth',
  path: '/mototaxista/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaAguardandoRoute = MototaxistaAguardandoRouteImport.update({
  id: '/mototaxista/aguardando',
  path: '/mototaxista/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoPerfilRoute = MercadoPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoPedidosRoute = MercadoPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoCheckoutRoute = MercadoCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoCarrinhoRoute = MercadoCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoBuscarRoute = MercadoBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => MercadoRoute,
} as any)
const FoodHomeRoute = FoodHomeRouteImport.update({
  id: '/food/home',
  path: '/food/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodEsqueciPinRoute = FoodEsqueciPinRouteImport.update({
  id: '/food/esqueci-pin',
  path: '/food/esqueci-pin',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodCadastroRoute = FoodCadastroRouteImport.update({
  id: '/food/cadastro',
  path: '/food/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodAuthRoute = FoodAuthRouteImport.update({
  id: '/food/auth',
  path: '/food/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EstabelecimentoPainelRoute = EstabelecimentoPainelRouteImport.update({
  id: '/estabelecimento/painel',
  path: '/estabelecimento/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const EstabelecimentoMercadoRoute = EstabelecimentoMercadoRouteImport.update({
  id: '/estabelecimento/mercado',
  path: '/estabelecimento/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaHomeRoute = EmpresaHomeRouteImport.update({
  id: '/empresa/home',
  path: '/empresa/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaCadastroRoute = EmpresaCadastroRouteImport.update({
  id: '/empresa/cadastro',
  path: '/empresa/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaAuthRoute = EmpresaAuthRouteImport.update({
  id: '/empresa/auth',
  path: '/empresa/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadeServicosRoute = CidadeServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => CidadeRoute,
} as any)
const CadastroPassageiroRoute = CadastroPassageiroRouteImport.update({
  id: '/cadastro/passageiro',
  path: '/cadastro/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPassageiroRoute = AuthPassageiroRouteImport.update({
  id: '/auth/passageiro',
  path: '/auth/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMototaxistaRoute = AuthMototaxistaRouteImport.update({
  id: '/auth/mototaxista',
  path: '/auth/mototaxista',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPassageiroRoute = AppPassageiroRouteImport.update({
  id: '/app/passageiro',
  path: '/app/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppParceirosRoute = AppParceirosRouteImport.update({
  id: '/app/parceiros',
  path: '/app/parceiros',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMototaxiRoute = AppMototaxiRouteImport.update({
  id: '/app/mototaxi',
  path: '/app/mototaxi',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/app/entregas',
  path: '/app/entregas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdministradorRoute = AppAdministradorRouteImport.update({
  id: '/app/administrador',
  path: '/app/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmSuspensoRoute = AdmSuspensoRouteImport.update({
  id: '/suspenso',
  path: '/suspenso',
  getParentRoute: () => AdmRoute,
} as any)
const AdmNegadoRoute = AdmNegadoRouteImport.update({
  id: '/negado',
  path: '/negado',
  getParentRoute: () => AdmRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PedirProdutoIdRoute = PedirProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => PedirRoute,
} as any)
const PedirLojaIdRoute = PedirLojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => PedirRoute,
} as any)
const PedirConfirmadoIdRoute = PedirConfirmadoIdRouteImport.update({
  id: '/confirmado/$id',
  path: '/confirmado/$id',
  getParentRoute: () => PedirRoute,
} as any)
const PedirAcompanharIdRoute = PedirAcompanharIdRouteImport.update({
  id: '/acompanhar/$id',
  path: '/acompanhar/$id',
  getParentRoute: () => PedirRoute,
} as any)
const MercadoProdutoIdRoute = MercadoProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoLojaIdRoute = MercadoLojaIdRouteImport.update({
  id: '/loja/$id',
  path: '/loja/$id',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoConfirmadoIdRoute = MercadoConfirmadoIdRouteImport.update({
  id: '/confirmado/$id',
  path: '/confirmado/$id',
  getParentRoute: () => MercadoRoute,
} as any)
const MercadoAcompanharIdRoute = MercadoAcompanharIdRouteImport.update({
  id: '/acompanhar/$id',
  path: '/acompanhar/$id',
  getParentRoute: () => MercadoRoute,
} as any)
const AdmGateAdmPrecosRoute = AdmGateAdmPrecosRouteImport.update({
  id: '/adm/precos',
  path: '/adm/precos',
  getParentRoute: () => AdmGateRoute,
} as any)
const AdmGateAdmPainelRoute = AdmGateAdmPainelRouteImport.update({
  id: '/adm/painel',
  path: '/adm/painel',
  getParentRoute: () => AdmGateRoute,
} as any)
const AdmGateAdmGestaoRoute = AdmGateAdmGestaoRouteImport.update({
  id: '/adm/gestao',
  path: '/adm/gestao',
  getParentRoute: () => AdmGateRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRouteWithChildren
  '/admin': typeof AdminRoute
  '/administrador': typeof AdministradorRoute
  '/cidade': typeof CidadeRouteWithChildren
  '/entregas': typeof EntregasRoute
  '/escolher': typeof EscolherRoute
  '/mcp': typeof McpRoute
  '/mercado': typeof MercadoRouteWithChildren
  '/mototaxi': typeof MototaxiRoute
  '/parceiros': typeof ParceirosRouteWithChildren
  '/pedir': typeof PedirRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/adm/negado': typeof AdmNegadoRoute
  '/adm/suspenso': typeof AdmSuspensoRoute
  '/app/administrador': typeof AppAdministradorRoute
  '/app/entregas': typeof AppEntregasRoute
  '/app/mototaxi': typeof AppMototaxiRoute
  '/app/parceiros': typeof AppParceirosRoute
  '/app/passageiro': typeof AppPassageiroRoute
  '/auth/mototaxista': typeof AuthMototaxistaRoute
  '/auth/passageiro': typeof AuthPassageiroRoute
  '/cadastro/passageiro': typeof CadastroPassageiroRoute
  '/cidade/servicos': typeof CidadeServicosRoute
  '/empresa/auth': typeof EmpresaAuthRoute
  '/empresa/cadastro': typeof EmpresaCadastroRoute
  '/empresa/home': typeof EmpresaHomeRoute
  '/estabelecimento/mercado': typeof EstabelecimentoMercadoRoute
  '/estabelecimento/painel': typeof EstabelecimentoPainelRoute
  '/food/auth': typeof FoodAuthRoute
  '/food/cadastro': typeof FoodCadastroRoute
  '/food/esqueci-pin': typeof FoodEsqueciPinRoute
  '/food/home': typeof FoodHomeRoute
  '/mercado/buscar': typeof MercadoBuscarRoute
  '/mercado/carrinho': typeof MercadoCarrinhoRoute
  '/mercado/checkout': typeof MercadoCheckoutRoute
  '/mercado/pedidos': typeof MercadoPedidosRoute
  '/mercado/perfil': typeof MercadoPerfilRoute
  '/mototaxista/aguardando': typeof MototaxistaAguardandoRoute
  '/mototaxista/auth': typeof MototaxistaAuthRoute
  '/mototaxista/cadastro': typeof MototaxistaCadastroRoute
  '/mototaxista/documentos': typeof MototaxistaDocumentosRoute
  '/mototaxista/food': typeof MototaxistaFoodRoute
  '/mototaxista/foto': typeof MototaxistaFotoRoute
  '/mototaxista/home': typeof MototaxistaHomeRoute
  '/mototaxista/mercado': typeof MototaxistaMercadoRoute
  '/mototaxista/pagamento': typeof MototaxistaPagamentoRoute
  '/mototaxista/planos': typeof MototaxistaPlanosRoute
  '/parceiros/auth': typeof ParceirosAuthRoute
  '/parceiros/cadastro': typeof ParceirosCadastroRoute
  '/parceiros/mercado': typeof ParceirosMercadoRoute
  '/parceiros/painel': typeof ParceirosPainelRoute
  '/passageiro/carteira': typeof PassageiroCarteiraRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/home': typeof PassageiroHomeRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/pedir/buscar': typeof PedirBuscarRoute
  '/pedir/carrinho': typeof PedirCarrinhoRoute
  '/pedir/categorias': typeof PedirCategoriasRoute
  '/pedir/checkout': typeof PedirCheckoutRoute
  '/pedir/pedidos': typeof PedirPedidosRoute
  '/pedir/perfil': typeof PedirPerfilRoute
  '/cidade/': typeof CidadeIndexRoute
  '/food/': typeof FoodIndexRoute
  '/mercado/': typeof MercadoIndexRoute
  '/mototaxista/': typeof MototaxistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/pedir/': typeof PedirIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/adm/gestao': typeof AdmGateAdmGestaoRoute
  '/adm/painel': typeof AdmGateAdmPainelRoute
  '/adm/precos': typeof AdmGateAdmPrecosRoute
  '/mercado/acompanhar/$id': typeof MercadoAcompanharIdRoute
  '/mercado/confirmado/$id': typeof MercadoConfirmadoIdRoute
  '/mercado/loja/$id': typeof MercadoLojaIdRoute
  '/mercado/produto/$id': typeof MercadoProdutoIdRoute
  '/pedir/acompanhar/$id': typeof PedirAcompanharIdRoute
  '/pedir/confirmado/$id': typeof PedirConfirmadoIdRoute
  '/pedir/loja/$id': typeof PedirLojaIdRoute
  '/pedir/produto/$id': typeof PedirProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm': typeof AdmRouteWithChildren
  '/admin': typeof AdminRoute
  '/administrador': typeof AdministradorRoute
  '/entregas': typeof EntregasRoute
  '/escolher': typeof EscolherRoute
  '/mcp': typeof McpRoute
  '/mototaxi': typeof MototaxiRoute
  '/parceiros': typeof ParceirosRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/adm/negado': typeof AdmNegadoRoute
  '/adm/suspenso': typeof AdmSuspensoRoute
  '/app/administrador': typeof AppAdministradorRoute
  '/app/entregas': typeof AppEntregasRoute
  '/app/mototaxi': typeof AppMototaxiRoute
  '/app/parceiros': typeof AppParceirosRoute
  '/app/passageiro': typeof AppPassageiroRoute
  '/auth/mototaxista': typeof AuthMototaxistaRoute
  '/auth/passageiro': typeof AuthPassageiroRoute
  '/cadastro/passageiro': typeof CadastroPassageiroRoute
  '/cidade/servicos': typeof CidadeServicosRoute
  '/empresa/auth': typeof EmpresaAuthRoute
  '/empresa/cadastro': typeof EmpresaCadastroRoute
  '/empresa/home': typeof EmpresaHomeRoute
  '/estabelecimento/mercado': typeof EstabelecimentoMercadoRoute
  '/estabelecimento/painel': typeof EstabelecimentoPainelRoute
  '/food/auth': typeof FoodAuthRoute
  '/food/cadastro': typeof FoodCadastroRoute
  '/food/esqueci-pin': typeof FoodEsqueciPinRoute
  '/food/home': typeof FoodHomeRoute
  '/mercado/buscar': typeof MercadoBuscarRoute
  '/mercado/carrinho': typeof MercadoCarrinhoRoute
  '/mercado/checkout': typeof MercadoCheckoutRoute
  '/mercado/pedidos': typeof MercadoPedidosRoute
  '/mercado/perfil': typeof MercadoPerfilRoute
  '/mototaxista/aguardando': typeof MototaxistaAguardandoRoute
  '/mototaxista/auth': typeof MototaxistaAuthRoute
  '/mototaxista/cadastro': typeof MototaxistaCadastroRoute
  '/mototaxista/documentos': typeof MototaxistaDocumentosRoute
  '/mototaxista/food': typeof MototaxistaFoodRoute
  '/mototaxista/foto': typeof MototaxistaFotoRoute
  '/mototaxista/home': typeof MototaxistaHomeRoute
  '/mototaxista/mercado': typeof MototaxistaMercadoRoute
  '/mototaxista/pagamento': typeof MototaxistaPagamentoRoute
  '/mototaxista/planos': typeof MototaxistaPlanosRoute
  '/parceiros/auth': typeof ParceirosAuthRoute
  '/parceiros/cadastro': typeof ParceirosCadastroRoute
  '/parceiros/mercado': typeof ParceirosMercadoRoute
  '/parceiros/painel': typeof ParceirosPainelRoute
  '/passageiro/carteira': typeof PassageiroCarteiraRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/home': typeof PassageiroHomeRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/pedir/buscar': typeof PedirBuscarRoute
  '/pedir/carrinho': typeof PedirCarrinhoRoute
  '/pedir/categorias': typeof PedirCategoriasRoute
  '/pedir/checkout': typeof PedirCheckoutRoute
  '/pedir/pedidos': typeof PedirPedidosRoute
  '/pedir/perfil': typeof PedirPerfilRoute
  '/cidade': typeof CidadeIndexRoute
  '/food': typeof FoodIndexRoute
  '/mercado': typeof MercadoIndexRoute
  '/mototaxista': typeof MototaxistaIndexRoute
  '/passageiro': typeof PassageiroIndexRoute
  '/pedir': typeof PedirIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/adm/gestao': typeof AdmGateAdmGestaoRoute
  '/adm/painel': typeof AdmGateAdmPainelRoute
  '/adm/precos': typeof AdmGateAdmPrecosRoute
  '/mercado/acompanhar/$id': typeof MercadoAcompanharIdRoute
  '/mercado/confirmado/$id': typeof MercadoConfirmadoIdRoute
  '/mercado/loja/$id': typeof MercadoLojaIdRoute
  '/mercado/produto/$id': typeof MercadoProdutoIdRoute
  '/pedir/acompanhar/$id': typeof PedirAcompanharIdRoute
  '/pedir/confirmado/$id': typeof PedirConfirmadoIdRoute
  '/pedir/loja/$id': typeof PedirLojaIdRoute
  '/pedir/produto/$id': typeof PedirProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admGate': typeof AdmGateRouteWithChildren
  '/adm': typeof AdmRouteWithChildren
  '/admin': typeof AdminRoute
  '/administrador': typeof AdministradorRoute
  '/cidade': typeof CidadeRouteWithChildren
  '/entregas': typeof EntregasRoute
  '/escolher': typeof EscolherRoute
  '/mcp': typeof McpRoute
  '/mercado': typeof MercadoRouteWithChildren
  '/mototaxi': typeof MototaxiRoute
  '/parceiros': typeof ParceirosRouteWithChildren
  '/pedir': typeof PedirRouteWithChildren
  '/privacidade': typeof PrivacidadeRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/adm/negado': typeof AdmNegadoRoute
  '/adm/suspenso': typeof AdmSuspensoRoute
  '/app/administrador': typeof AppAdministradorRoute
  '/app/entregas': typeof AppEntregasRoute
  '/app/mototaxi': typeof AppMototaxiRoute
  '/app/parceiros': typeof AppParceirosRoute
  '/app/passageiro': typeof AppPassageiroRoute
  '/auth/mototaxista': typeof AuthMototaxistaRoute
  '/auth/passageiro': typeof AuthPassageiroRoute
  '/cadastro/passageiro': typeof CadastroPassageiroRoute
  '/cidade/servicos': typeof CidadeServicosRoute
  '/empresa/auth': typeof EmpresaAuthRoute
  '/empresa/cadastro': typeof EmpresaCadastroRoute
  '/empresa/home': typeof EmpresaHomeRoute
  '/estabelecimento/mercado': typeof EstabelecimentoMercadoRoute
  '/estabelecimento/painel': typeof EstabelecimentoPainelRoute
  '/food/auth': typeof FoodAuthRoute
  '/food/cadastro': typeof FoodCadastroRoute
  '/food/esqueci-pin': typeof FoodEsqueciPinRoute
  '/food/home': typeof FoodHomeRoute
  '/mercado/buscar': typeof MercadoBuscarRoute
  '/mercado/carrinho': typeof MercadoCarrinhoRoute
  '/mercado/checkout': typeof MercadoCheckoutRoute
  '/mercado/pedidos': typeof MercadoPedidosRoute
  '/mercado/perfil': typeof MercadoPerfilRoute
  '/mototaxista/aguardando': typeof MototaxistaAguardandoRoute
  '/mototaxista/auth': typeof MototaxistaAuthRoute
  '/mototaxista/cadastro': typeof MototaxistaCadastroRoute
  '/mototaxista/documentos': typeof MototaxistaDocumentosRoute
  '/mototaxista/food': typeof MototaxistaFoodRoute
  '/mototaxista/foto': typeof MototaxistaFotoRoute
  '/mototaxista/home': typeof MototaxistaHomeRoute
  '/mototaxista/mercado': typeof MototaxistaMercadoRoute
  '/mototaxista/pagamento': typeof MototaxistaPagamentoRoute
  '/mototaxista/planos': typeof MototaxistaPlanosRoute
  '/parceiros/auth': typeof ParceirosAuthRoute
  '/parceiros/cadastro': typeof ParceirosCadastroRoute
  '/parceiros/mercado': typeof ParceirosMercadoRoute
  '/parceiros/painel': typeof ParceirosPainelRoute
  '/passageiro/carteira': typeof PassageiroCarteiraRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/home': typeof PassageiroHomeRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/pedir/buscar': typeof PedirBuscarRoute
  '/pedir/carrinho': typeof PedirCarrinhoRoute
  '/pedir/categorias': typeof PedirCategoriasRoute
  '/pedir/checkout': typeof PedirCheckoutRoute
  '/pedir/pedidos': typeof PedirPedidosRoute
  '/pedir/perfil': typeof PedirPerfilRoute
  '/cidade/': typeof CidadeIndexRoute
  '/food/': typeof FoodIndexRoute
  '/mercado/': typeof MercadoIndexRoute
  '/mototaxista/': typeof MototaxistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/pedir/': typeof PedirIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_admGate/adm/gestao': typeof AdmGateAdmGestaoRoute
  '/_admGate/adm/painel': typeof AdmGateAdmPainelRoute
  '/_admGate/adm/precos': typeof AdmGateAdmPrecosRoute
  '/mercado/acompanhar/$id': typeof MercadoAcompanharIdRoute
  '/mercado/confirmado/$id': typeof MercadoConfirmadoIdRoute
  '/mercado/loja/$id': typeof MercadoLojaIdRoute
  '/mercado/produto/$id': typeof MercadoProdutoIdRoute
  '/pedir/acompanhar/$id': typeof PedirAcompanharIdRoute
  '/pedir/confirmado/$id': typeof PedirConfirmadoIdRoute
  '/pedir/loja/$id': typeof PedirLojaIdRoute
  '/pedir/produto/$id': typeof PedirProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/admin'
    | '/administrador'
    | '/cidade'
    | '/entregas'
    | '/escolher'
    | '/mcp'
    | '/mercado'
    | '/mototaxi'
    | '/parceiros'
    | '/pedir'
    | '/privacidade'
    | '/splash'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/adm/negado'
    | '/adm/suspenso'
    | '/app/administrador'
    | '/app/entregas'
    | '/app/mototaxi'
    | '/app/parceiros'
    | '/app/passageiro'
    | '/auth/mototaxista'
    | '/auth/passageiro'
    | '/cadastro/passageiro'
    | '/cidade/servicos'
    | '/empresa/auth'
    | '/empresa/cadastro'
    | '/empresa/home'
    | '/estabelecimento/mercado'
    | '/estabelecimento/painel'
    | '/food/auth'
    | '/food/cadastro'
    | '/food/esqueci-pin'
    | '/food/home'
    | '/mercado/buscar'
    | '/mercado/carrinho'
    | '/mercado/checkout'
    | '/mercado/pedidos'
    | '/mercado/perfil'
    | '/mototaxista/aguardando'
    | '/mototaxista/auth'
    | '/mototaxista/cadastro'
    | '/mototaxista/documentos'
    | '/mototaxista/food'
    | '/mototaxista/foto'
    | '/mototaxista/home'
    | '/mototaxista/mercado'
    | '/mototaxista/pagamento'
    | '/mototaxista/planos'
    | '/parceiros/auth'
    | '/parceiros/cadastro'
    | '/parceiros/mercado'
    | '/parceiros/painel'
    | '/passageiro/carteira'
    | '/passageiro/corridas'
    | '/passageiro/home'
    | '/passageiro/perfil'
    | '/pedir/buscar'
    | '/pedir/carrinho'
    | '/pedir/categorias'
    | '/pedir/checkout'
    | '/pedir/pedidos'
    | '/pedir/perfil'
    | '/cidade/'
    | '/food/'
    | '/mercado/'
    | '/mototaxista/'
    | '/passageiro/'
    | '/pedir/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/adm/gestao'
    | '/adm/painel'
    | '/adm/precos'
    | '/mercado/acompanhar/$id'
    | '/mercado/confirmado/$id'
    | '/mercado/loja/$id'
    | '/mercado/produto/$id'
    | '/pedir/acompanhar/$id'
    | '/pedir/confirmado/$id'
    | '/pedir/loja/$id'
    | '/pedir/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm'
    | '/admin'
    | '/administrador'
    | '/entregas'
    | '/escolher'
    | '/mcp'
    | '/mototaxi'
    | '/parceiros'
    | '/privacidade'
    | '/splash'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/adm/negado'
    | '/adm/suspenso'
    | '/app/administrador'
    | '/app/entregas'
    | '/app/mototaxi'
    | '/app/parceiros'
    | '/app/passageiro'
    | '/auth/mototaxista'
    | '/auth/passageiro'
    | '/cadastro/passageiro'
    | '/cidade/servicos'
    | '/empresa/auth'
    | '/empresa/cadastro'
    | '/empresa/home'
    | '/estabelecimento/mercado'
    | '/estabelecimento/painel'
    | '/food/auth'
    | '/food/cadastro'
    | '/food/esqueci-pin'
    | '/food/home'
    | '/mercado/buscar'
    | '/mercado/carrinho'
    | '/mercado/checkout'
    | '/mercado/pedidos'
    | '/mercado/perfil'
    | '/mototaxista/aguardando'
    | '/mototaxista/auth'
    | '/mototaxista/cadastro'
    | '/mototaxista/documentos'
    | '/mototaxista/food'
    | '/mototaxista/foto'
    | '/mototaxista/home'
    | '/mototaxista/mercado'
    | '/mototaxista/pagamento'
    | '/mototaxista/planos'
    | '/parceiros/auth'
    | '/parceiros/cadastro'
    | '/parceiros/mercado'
    | '/parceiros/painel'
    | '/passageiro/carteira'
    | '/passageiro/corridas'
    | '/passageiro/home'
    | '/passageiro/perfil'
    | '/pedir/buscar'
    | '/pedir/carrinho'
    | '/pedir/categorias'
    | '/pedir/checkout'
    | '/pedir/pedidos'
    | '/pedir/perfil'
    | '/cidade'
    | '/food'
    | '/mercado'
    | '/mototaxista'
    | '/passageiro'
    | '/pedir'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/adm/gestao'
    | '/adm/painel'
    | '/adm/precos'
    | '/mercado/acompanhar/$id'
    | '/mercado/confirmado/$id'
    | '/mercado/loja/$id'
    | '/mercado/produto/$id'
    | '/pedir/acompanhar/$id'
    | '/pedir/confirmado/$id'
    | '/pedir/loja/$id'
    | '/pedir/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/_admGate'
    | '/adm'
    | '/admin'
    | '/administrador'
    | '/cidade'
    | '/entregas'
    | '/escolher'
    | '/mcp'
    | '/mercado'
    | '/mototaxi'
    | '/parceiros'
    | '/pedir'
    | '/privacidade'
    | '/splash'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/adm/negado'
    | '/adm/suspenso'
    | '/app/administrador'
    | '/app/entregas'
    | '/app/mototaxi'
    | '/app/parceiros'
    | '/app/passageiro'
    | '/auth/mototaxista'
    | '/auth/passageiro'
    | '/cadastro/passageiro'
    | '/cidade/servicos'
    | '/empresa/auth'
    | '/empresa/cadastro'
    | '/empresa/home'
    | '/estabelecimento/mercado'
    | '/estabelecimento/painel'
    | '/food/auth'
    | '/food/cadastro'
    | '/food/esqueci-pin'
    | '/food/home'
    | '/mercado/buscar'
    | '/mercado/carrinho'
    | '/mercado/checkout'
    | '/mercado/pedidos'
    | '/mercado/perfil'
    | '/mototaxista/aguardando'
    | '/mototaxista/auth'
    | '/mototaxista/cadastro'
    | '/mototaxista/documentos'
    | '/mototaxista/food'
    | '/mototaxista/foto'
    | '/mototaxista/home'
    | '/mototaxista/mercado'
    | '/mototaxista/pagamento'
    | '/mototaxista/planos'
    | '/parceiros/auth'
    | '/parceiros/cadastro'
    | '/parceiros/mercado'
    | '/parceiros/painel'
    | '/passageiro/carteira'
    | '/passageiro/corridas'
    | '/passageiro/home'
    | '/passageiro/perfil'
    | '/pedir/buscar'
    | '/pedir/carrinho'
    | '/pedir/categorias'
    | '/pedir/checkout'
    | '/pedir/pedidos'
    | '/pedir/perfil'
    | '/cidade/'
    | '/food/'
    | '/mercado/'
    | '/mototaxista/'
    | '/passageiro/'
    | '/pedir/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_admGate/adm/gestao'
    | '/_admGate/adm/painel'
    | '/_admGate/adm/precos'
    | '/mercado/acompanhar/$id'
    | '/mercado/confirmado/$id'
    | '/mercado/loja/$id'
    | '/mercado/produto/$id'
    | '/pedir/acompanhar/$id'
    | '/pedir/confirmado/$id'
    | '/pedir/loja/$id'
    | '/pedir/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmGateRoute: typeof AdmGateRouteWithChildren
  AdmRoute: typeof AdmRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdministradorRoute: typeof AdministradorRoute
  CidadeRoute: typeof CidadeRouteWithChildren
  EntregasRoute: typeof EntregasRoute
  EscolherRoute: typeof EscolherRoute
  McpRoute: typeof McpRoute
  MercadoRoute: typeof MercadoRouteWithChildren
  MototaxiRoute: typeof MototaxiRoute
  ParceirosRoute: typeof ParceirosRouteWithChildren
  PedirRoute: typeof PedirRouteWithChildren
  PrivacidadeRoute: typeof PrivacidadeRoute
  SplashRoute: typeof SplashRoute
  TermosRoute: typeof TermosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AppAdministradorRoute: typeof AppAdministradorRoute
  AppEntregasRoute: typeof AppEntregasRoute
  AppMototaxiRoute: typeof AppMototaxiRoute
  AppParceirosRoute: typeof AppParceirosRoute
  AppPassageiroRoute: typeof AppPassageiroRoute
  AuthMototaxistaRoute: typeof AuthMototaxistaRoute
  AuthPassageiroRoute: typeof AuthPassageiroRoute
  CadastroPassageiroRoute: typeof CadastroPassageiroRoute
  EmpresaAuthRoute: typeof EmpresaAuthRoute
  EmpresaCadastroRoute: typeof EmpresaCadastroRoute
  EmpresaHomeRoute: typeof EmpresaHomeRoute
  EstabelecimentoMercadoRoute: typeof EstabelecimentoMercadoRoute
  EstabelecimentoPainelRoute: typeof EstabelecimentoPainelRoute
  FoodAuthRoute: typeof FoodAuthRoute
  FoodCadastroRoute: typeof FoodCadastroRoute
  FoodEsqueciPinRoute: typeof FoodEsqueciPinRoute
  FoodHomeRoute: typeof FoodHomeRoute
  MototaxistaAguardandoRoute: typeof MototaxistaAguardandoRoute
  MototaxistaAuthRoute: typeof MototaxistaAuthRoute
  MototaxistaCadastroRoute: typeof MototaxistaCadastroRoute
  MototaxistaDocumentosRoute: typeof MototaxistaDocumentosRoute
  MototaxistaFoodRoute: typeof MototaxistaFoodRoute
  MototaxistaFotoRoute: typeof MototaxistaFotoRoute
  MototaxistaHomeRoute: typeof MototaxistaHomeRoute
  MototaxistaMercadoRoute: typeof MototaxistaMercadoRoute
  MototaxistaPagamentoRoute: typeof MototaxistaPagamentoRoute
  MototaxistaPlanosRoute: typeof MototaxistaPlanosRoute
  PassageiroCarteiraRoute: typeof PassageiroCarteiraRoute
  PassageiroCorridasRoute: typeof PassageiroCorridasRoute
  PassageiroHomeRoute: typeof PassageiroHomeRoute
  PassageiroPerfilRoute: typeof PassageiroPerfilRoute
  FoodIndexRoute: typeof FoodIndexRoute
  MototaxistaIndexRoute: typeof MototaxistaIndexRoute
  PassageiroIndexRoute: typeof PassageiroIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir': {
      id: '/pedir'
      path: '/pedir'
      fullPath: '/pedir'
      preLoaderRoute: typeof PedirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros': {
      id: '/parceiros'
      path: '/parceiros'
      fullPath: '/parceiros'
      preLoaderRoute: typeof ParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxi': {
      id: '/mototaxi'
      path: '/mototaxi'
      fullPath: '/mototaxi'
      preLoaderRoute: typeof MototaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escolher': {
      id: '/escolher'
      path: '/escolher'
      fullPath: '/escolher'
      preLoaderRoute: typeof EscolherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregas': {
      id: '/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof EntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidade': {
      id: '/cidade'
      path: '/cidade'
      fullPath: '/cidade'
      preLoaderRoute: typeof CidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrador': {
      id: '/administrador'
      path: '/administrador'
      fullPath: '/administrador'
      preLoaderRoute: typeof AdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm': {
      id: '/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admGate': {
      id: '/_admGate'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdmGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir/': {
      id: '/pedir/'
      path: '/'
      fullPath: '/pedir/'
      preLoaderRoute: typeof PedirIndexRouteImport
      parentRoute: typeof PedirRoute
    }
    '/passageiro/': {
      id: '/passageiro/'
      path: '/passageiro'
      fullPath: '/passageiro/'
      preLoaderRoute: typeof PassageiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/': {
      id: '/mototaxista/'
      path: '/mototaxista'
      fullPath: '/mototaxista/'
      preLoaderRoute: typeof MototaxistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado/': {
      id: '/mercado/'
      path: '/'
      fullPath: '/mercado/'
      preLoaderRoute: typeof MercadoIndexRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/food/': {
      id: '/food/'
      path: '/food'
      fullPath: '/food/'
      preLoaderRoute: typeof FoodIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidade/': {
      id: '/cidade/'
      path: '/'
      fullPath: '/cidade/'
      preLoaderRoute: typeof CidadeIndexRouteImport
      parentRoute: typeof CidadeRoute
    }
    '/pedir/perfil': {
      id: '/pedir/perfil'
      path: '/perfil'
      fullPath: '/pedir/perfil'
      preLoaderRoute: typeof PedirPerfilRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/pedidos': {
      id: '/pedir/pedidos'
      path: '/pedidos'
      fullPath: '/pedir/pedidos'
      preLoaderRoute: typeof PedirPedidosRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/checkout': {
      id: '/pedir/checkout'
      path: '/checkout'
      fullPath: '/pedir/checkout'
      preLoaderRoute: typeof PedirCheckoutRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/categorias': {
      id: '/pedir/categorias'
      path: '/categorias'
      fullPath: '/pedir/categorias'
      preLoaderRoute: typeof PedirCategoriasRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/carrinho': {
      id: '/pedir/carrinho'
      path: '/carrinho'
      fullPath: '/pedir/carrinho'
      preLoaderRoute: typeof PedirCarrinhoRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/buscar': {
      id: '/pedir/buscar'
      path: '/buscar'
      fullPath: '/pedir/buscar'
      preLoaderRoute: typeof PedirBuscarRouteImport
      parentRoute: typeof PedirRoute
    }
    '/passageiro/perfil': {
      id: '/passageiro/perfil'
      path: '/passageiro/perfil'
      fullPath: '/passageiro/perfil'
      preLoaderRoute: typeof PassageiroPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/home': {
      id: '/passageiro/home'
      path: '/passageiro/home'
      fullPath: '/passageiro/home'
      preLoaderRoute: typeof PassageiroHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/corridas': {
      id: '/passageiro/corridas'
      path: '/passageiro/corridas'
      fullPath: '/passageiro/corridas'
      preLoaderRoute: typeof PassageiroCorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/carteira': {
      id: '/passageiro/carteira'
      path: '/passageiro/carteira'
      fullPath: '/passageiro/carteira'
      preLoaderRoute: typeof PassageiroCarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parceiros/painel': {
      id: '/parceiros/painel'
      path: '/painel'
      fullPath: '/parceiros/painel'
      preLoaderRoute: typeof ParceirosPainelRouteImport
      parentRoute: typeof ParceirosRoute
    }
    '/parceiros/mercado': {
      id: '/parceiros/mercado'
      path: '/mercado'
      fullPath: '/parceiros/mercado'
      preLoaderRoute: typeof ParceirosMercadoRouteImport
      parentRoute: typeof ParceirosRoute
    }
    '/parceiros/cadastro': {
      id: '/parceiros/cadastro'
      path: '/cadastro'
      fullPath: '/parceiros/cadastro'
      preLoaderRoute: typeof ParceirosCadastroRouteImport
      parentRoute: typeof ParceirosRoute
    }
    '/parceiros/auth': {
      id: '/parceiros/auth'
      path: '/auth'
      fullPath: '/parceiros/auth'
      preLoaderRoute: typeof ParceirosAuthRouteImport
      parentRoute: typeof ParceirosRoute
    }
    '/mototaxista/planos': {
      id: '/mototaxista/planos'
      path: '/mototaxista/planos'
      fullPath: '/mototaxista/planos'
      preLoaderRoute: typeof MototaxistaPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/pagamento': {
      id: '/mototaxista/pagamento'
      path: '/mototaxista/pagamento'
      fullPath: '/mototaxista/pagamento'
      preLoaderRoute: typeof MototaxistaPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/mercado': {
      id: '/mototaxista/mercado'
      path: '/mototaxista/mercado'
      fullPath: '/mototaxista/mercado'
      preLoaderRoute: typeof MototaxistaMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/home': {
      id: '/mototaxista/home'
      path: '/mototaxista/home'
      fullPath: '/mototaxista/home'
      preLoaderRoute: typeof MototaxistaHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/foto': {
      id: '/mototaxista/foto'
      path: '/mototaxista/foto'
      fullPath: '/mototaxista/foto'
      preLoaderRoute: typeof MototaxistaFotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/food': {
      id: '/mototaxista/food'
      path: '/mototaxista/food'
      fullPath: '/mototaxista/food'
      preLoaderRoute: typeof MototaxistaFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/documentos': {
      id: '/mototaxista/documentos'
      path: '/mototaxista/documentos'
      fullPath: '/mototaxista/documentos'
      preLoaderRoute: typeof MototaxistaDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/cadastro': {
      id: '/mototaxista/cadastro'
      path: '/mototaxista/cadastro'
      fullPath: '/mototaxista/cadastro'
      preLoaderRoute: typeof MototaxistaCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/auth': {
      id: '/mototaxista/auth'
      path: '/mototaxista/auth'
      fullPath: '/mototaxista/auth'
      preLoaderRoute: typeof MototaxistaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/aguardando': {
      id: '/mototaxista/aguardando'
      path: '/mototaxista/aguardando'
      fullPath: '/mototaxista/aguardando'
      preLoaderRoute: typeof MototaxistaAguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado/perfil': {
      id: '/mercado/perfil'
      path: '/perfil'
      fullPath: '/mercado/perfil'
      preLoaderRoute: typeof MercadoPerfilRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/pedidos': {
      id: '/mercado/pedidos'
      path: '/pedidos'
      fullPath: '/mercado/pedidos'
      preLoaderRoute: typeof MercadoPedidosRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/checkout': {
      id: '/mercado/checkout'
      path: '/checkout'
      fullPath: '/mercado/checkout'
      preLoaderRoute: typeof MercadoCheckoutRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/carrinho': {
      id: '/mercado/carrinho'
      path: '/carrinho'
      fullPath: '/mercado/carrinho'
      preLoaderRoute: typeof MercadoCarrinhoRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/buscar': {
      id: '/mercado/buscar'
      path: '/buscar'
      fullPath: '/mercado/buscar'
      preLoaderRoute: typeof MercadoBuscarRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/food/home': {
      id: '/food/home'
      path: '/food/home'
      fullPath: '/food/home'
      preLoaderRoute: typeof FoodHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/esqueci-pin': {
      id: '/food/esqueci-pin'
      path: '/food/esqueci-pin'
      fullPath: '/food/esqueci-pin'
      preLoaderRoute: typeof FoodEsqueciPinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/cadastro': {
      id: '/food/cadastro'
      path: '/food/cadastro'
      fullPath: '/food/cadastro'
      preLoaderRoute: typeof FoodCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food/auth': {
      id: '/food/auth'
      path: '/food/auth'
      fullPath: '/food/auth'
      preLoaderRoute: typeof FoodAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estabelecimento/painel': {
      id: '/estabelecimento/painel'
      path: '/estabelecimento/painel'
      fullPath: '/estabelecimento/painel'
      preLoaderRoute: typeof EstabelecimentoPainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estabelecimento/mercado': {
      id: '/estabelecimento/mercado'
      path: '/estabelecimento/mercado'
      fullPath: '/estabelecimento/mercado'
      preLoaderRoute: typeof EstabelecimentoMercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/home': {
      id: '/empresa/home'
      path: '/empresa/home'
      fullPath: '/empresa/home'
      preLoaderRoute: typeof EmpresaHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/cadastro': {
      id: '/empresa/cadastro'
      path: '/empresa/cadastro'
      fullPath: '/empresa/cadastro'
      preLoaderRoute: typeof EmpresaCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa/auth': {
      id: '/empresa/auth'
      path: '/empresa/auth'
      fullPath: '/empresa/auth'
      preLoaderRoute: typeof EmpresaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidade/servicos': {
      id: '/cidade/servicos'
      path: '/servicos'
      fullPath: '/cidade/servicos'
      preLoaderRoute: typeof CidadeServicosRouteImport
      parentRoute: typeof CidadeRoute
    }
    '/cadastro/passageiro': {
      id: '/cadastro/passageiro'
      path: '/cadastro/passageiro'
      fullPath: '/cadastro/passageiro'
      preLoaderRoute: typeof CadastroPassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/passageiro': {
      id: '/auth/passageiro'
      path: '/auth/passageiro'
      fullPath: '/auth/passageiro'
      preLoaderRoute: typeof AuthPassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mototaxista': {
      id: '/auth/mototaxista'
      path: '/auth/mototaxista'
      fullPath: '/auth/mototaxista'
      preLoaderRoute: typeof AuthMototaxistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/passageiro': {
      id: '/app/passageiro'
      path: '/app/passageiro'
      fullPath: '/app/passageiro'
      preLoaderRoute: typeof AppPassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/parceiros': {
      id: '/app/parceiros'
      path: '/app/parceiros'
      fullPath: '/app/parceiros'
      preLoaderRoute: typeof AppParceirosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mototaxi': {
      id: '/app/mototaxi'
      path: '/app/mototaxi'
      fullPath: '/app/mototaxi'
      preLoaderRoute: typeof AppMototaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/entregas': {
      id: '/app/entregas'
      path: '/app/entregas'
      fullPath: '/app/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/administrador': {
      id: '/app/administrador'
      path: '/app/administrador'
      fullPath: '/app/administrador'
      preLoaderRoute: typeof AppAdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm/suspenso': {
      id: '/adm/suspenso'
      path: '/suspenso'
      fullPath: '/adm/suspenso'
      preLoaderRoute: typeof AdmSuspensoRouteImport
      parentRoute: typeof AdmRoute
    }
    '/adm/negado': {
      id: '/adm/negado'
      path: '/negado'
      fullPath: '/adm/negado'
      preLoaderRoute: typeof AdmNegadoRouteImport
      parentRoute: typeof AdmRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedir/produto/$id': {
      id: '/pedir/produto/$id'
      path: '/produto/$id'
      fullPath: '/pedir/produto/$id'
      preLoaderRoute: typeof PedirProdutoIdRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/loja/$id': {
      id: '/pedir/loja/$id'
      path: '/loja/$id'
      fullPath: '/pedir/loja/$id'
      preLoaderRoute: typeof PedirLojaIdRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/confirmado/$id': {
      id: '/pedir/confirmado/$id'
      path: '/confirmado/$id'
      fullPath: '/pedir/confirmado/$id'
      preLoaderRoute: typeof PedirConfirmadoIdRouteImport
      parentRoute: typeof PedirRoute
    }
    '/pedir/acompanhar/$id': {
      id: '/pedir/acompanhar/$id'
      path: '/acompanhar/$id'
      fullPath: '/pedir/acompanhar/$id'
      preLoaderRoute: typeof PedirAcompanharIdRouteImport
      parentRoute: typeof PedirRoute
    }
    '/mercado/produto/$id': {
      id: '/mercado/produto/$id'
      path: '/produto/$id'
      fullPath: '/mercado/produto/$id'
      preLoaderRoute: typeof MercadoProdutoIdRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/loja/$id': {
      id: '/mercado/loja/$id'
      path: '/loja/$id'
      fullPath: '/mercado/loja/$id'
      preLoaderRoute: typeof MercadoLojaIdRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/confirmado/$id': {
      id: '/mercado/confirmado/$id'
      path: '/confirmado/$id'
      fullPath: '/mercado/confirmado/$id'
      preLoaderRoute: typeof MercadoConfirmadoIdRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/mercado/acompanhar/$id': {
      id: '/mercado/acompanhar/$id'
      path: '/acompanhar/$id'
      fullPath: '/mercado/acompanhar/$id'
      preLoaderRoute: typeof MercadoAcompanharIdRouteImport
      parentRoute: typeof MercadoRoute
    }
    '/_admGate/adm/precos': {
      id: '/_admGate/adm/precos'
      path: '/adm/precos'
      fullPath: '/adm/precos'
      preLoaderRoute: typeof AdmGateAdmPrecosRouteImport
      parentRoute: typeof AdmGateRoute
    }
    '/_admGate/adm/painel': {
      id: '/_admGate/adm/painel'
      path: '/adm/painel'
      fullPath: '/adm/painel'
      preLoaderRoute: typeof AdmGateAdmPainelRouteImport
      parentRoute: typeof AdmGateRoute
    }
    '/_admGate/adm/gestao': {
      id: '/_admGate/adm/gestao'
      path: '/adm/gestao'
      fullPath: '/adm/gestao'
      preLoaderRoute: typeof AdmGateAdmGestaoRouteImport
      parentRoute: typeof AdmGateRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdmGateRouteChildren {
  AdmGateAdmGestaoRoute: typeof AdmGateAdmGestaoRoute
  AdmGateAdmPainelRoute: typeof AdmGateAdmPainelRoute
  AdmGateAdmPrecosRoute: typeof AdmGateAdmPrecosRoute
}

const AdmGateRouteChildren: AdmGateRouteChildren = {
  AdmGateAdmGestaoRoute: AdmGateAdmGestaoRoute,
  AdmGateAdmPainelRoute: AdmGateAdmPainelRoute,
  AdmGateAdmPrecosRoute: AdmGateAdmPrecosRoute,
}

const AdmGateRouteWithChildren =
  AdmGateRoute._addFileChildren(AdmGateRouteChildren)

interface AdmRouteChildren {
  AdmNegadoRoute: typeof AdmNegadoRoute
  AdmSuspensoRoute: typeof AdmSuspensoRoute
}

const AdmRouteChildren: AdmRouteChildren = {
  AdmNegadoRoute: AdmNegadoRoute,
  AdmSuspensoRoute: AdmSuspensoRoute,
}

const AdmRouteWithChildren = AdmRoute._addFileChildren(AdmRouteChildren)

interface CidadeRouteChildren {
  CidadeServicosRoute: typeof CidadeServicosRoute
  CidadeIndexRoute: typeof CidadeIndexRoute
}

const CidadeRouteChildren: CidadeRouteChildren = {
  CidadeServicosRoute: CidadeServicosRoute,
  CidadeIndexRoute: CidadeIndexRoute,
}

const CidadeRouteWithChildren =
  CidadeRoute._addFileChildren(CidadeRouteChildren)

interface MercadoRouteChildren {
  MercadoBuscarRoute: typeof MercadoBuscarRoute
  MercadoCarrinhoRoute: typeof MercadoCarrinhoRoute
  MercadoCheckoutRoute: typeof MercadoCheckoutRoute
  MercadoPedidosRoute: typeof MercadoPedidosRoute
  MercadoPerfilRoute: typeof MercadoPerfilRoute
  MercadoIndexRoute: typeof MercadoIndexRoute
  MercadoAcompanharIdRoute: typeof MercadoAcompanharIdRoute
  MercadoConfirmadoIdRoute: typeof MercadoConfirmadoIdRoute
  MercadoLojaIdRoute: typeof MercadoLojaIdRoute
  MercadoProdutoIdRoute: typeof MercadoProdutoIdRoute
}

const MercadoRouteChildren: MercadoRouteChildren = {
  MercadoBuscarRoute: MercadoBuscarRoute,
  MercadoCarrinhoRoute: MercadoCarrinhoRoute,
  MercadoCheckoutRoute: MercadoCheckoutRoute,
  MercadoPedidosRoute: MercadoPedidosRoute,
  MercadoPerfilRoute: MercadoPerfilRoute,
  MercadoIndexRoute: MercadoIndexRoute,
  MercadoAcompanharIdRoute: MercadoAcompanharIdRoute,
  MercadoConfirmadoIdRoute: MercadoConfirmadoIdRoute,
  MercadoLojaIdRoute: MercadoLojaIdRoute,
  MercadoProdutoIdRoute: MercadoProdutoIdRoute,
}

const MercadoRouteWithChildren =
  MercadoRoute._addFileChildren(MercadoRouteChildren)

interface ParceirosRouteChildren {
  ParceirosAuthRoute: typeof ParceirosAuthRoute
  ParceirosCadastroRoute: typeof ParceirosCadastroRoute
  ParceirosMercadoRoute: typeof ParceirosMercadoRoute
  ParceirosPainelRoute: typeof ParceirosPainelRoute
}

const ParceirosRouteChildren: ParceirosRouteChildren = {
  ParceirosAuthRoute: ParceirosAuthRoute,
  ParceirosCadastroRoute: ParceirosCadastroRoute,
  ParceirosMercadoRoute: ParceirosMercadoRoute,
  ParceirosPainelRoute: ParceirosPainelRoute,
}

const ParceirosRouteWithChildren = ParceirosRoute._addFileChildren(
  ParceirosRouteChildren,
)

interface PedirRouteChildren {
  PedirBuscarRoute: typeof PedirBuscarRoute
  PedirCarrinhoRoute: typeof PedirCarrinhoRoute
  PedirCategoriasRoute: typeof PedirCategoriasRoute
  PedirCheckoutRoute: typeof PedirCheckoutRoute
  PedirPedidosRoute: typeof PedirPedidosRoute
  PedirPerfilRoute: typeof PedirPerfilRoute
  PedirIndexRoute: typeof PedirIndexRoute
  PedirAcompanharIdRoute: typeof PedirAcompanharIdRoute
  PedirConfirmadoIdRoute: typeof PedirConfirmadoIdRoute
  PedirLojaIdRoute: typeof PedirLojaIdRoute
  PedirProdutoIdRoute: typeof PedirProdutoIdRoute
}

const PedirRouteChildren: PedirRouteChildren = {
  PedirBuscarRoute: PedirBuscarRoute,
  PedirCarrinhoRoute: PedirCarrinhoRoute,
  PedirCategoriasRoute: PedirCategoriasRoute,
  PedirCheckoutRoute: PedirCheckoutRoute,
  PedirPedidosRoute: PedirPedidosRoute,
  PedirPerfilRoute: PedirPerfilRoute,
  PedirIndexRoute: PedirIndexRoute,
  PedirAcompanharIdRoute: PedirAcompanharIdRoute,
  PedirConfirmadoIdRoute: PedirConfirmadoIdRoute,
  PedirLojaIdRoute: PedirLojaIdRoute,
  PedirProdutoIdRoute: PedirProdutoIdRoute,
}

const PedirRouteWithChildren = PedirRoute._addFileChildren(PedirRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmGateRoute: AdmGateRouteWithChildren,
  AdmRoute: AdmRouteWithChildren,
  AdminRoute: AdminRoute,
  AdministradorRoute: AdministradorRoute,
  CidadeRoute: CidadeRouteWithChildren,
  EntregasRoute: EntregasRoute,
  EscolherRoute: EscolherRoute,
  McpRoute: McpRoute,
  MercadoRoute: MercadoRouteWithChildren,
  MototaxiRoute: MototaxiRoute,
  ParceirosRoute: ParceirosRouteWithChildren,
  PedirRoute: PedirRouteWithChildren,
  PrivacidadeRoute: PrivacidadeRoute,
  SplashRoute: SplashRoute,
  TermosRoute: TermosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AppAdministradorRoute: AppAdministradorRoute,
  AppEntregasRoute: AppEntregasRoute,
  AppMototaxiRoute: AppMototaxiRoute,
  AppParceirosRoute: AppParceirosRoute,
  AppPassageiroRoute: AppPassageiroRoute,
  AuthMototaxistaRoute: AuthMototaxistaRoute,
  AuthPassageiroRoute: AuthPassageiroRoute,
  CadastroPassageiroRoute: CadastroPassageiroRoute,
  EmpresaAuthRoute: EmpresaAuthRoute,
  EmpresaCadastroRoute: EmpresaCadastroRoute,
  EmpresaHomeRoute: EmpresaHomeRoute,
  EstabelecimentoMercadoRoute: EstabelecimentoMercadoRoute,
  EstabelecimentoPainelRoute: EstabelecimentoPainelRoute,
  FoodAuthRoute: FoodAuthRoute,
  FoodCadastroRoute: FoodCadastroRoute,
  FoodEsqueciPinRoute: FoodEsqueciPinRoute,
  FoodHomeRoute: FoodHomeRoute,
  MototaxistaAguardandoRoute: MototaxistaAguardandoRoute,
  MototaxistaAuthRoute: MototaxistaAuthRoute,
  MototaxistaCadastroRoute: MototaxistaCadastroRoute,
  MototaxistaDocumentosRoute: MototaxistaDocumentosRoute,
  MototaxistaFoodRoute: MototaxistaFoodRoute,
  MototaxistaFotoRoute: MototaxistaFotoRoute,
  MototaxistaHomeRoute: MototaxistaHomeRoute,
  MototaxistaMercadoRoute: MototaxistaMercadoRoute,
  MototaxistaPagamentoRoute: MototaxistaPagamentoRoute,
  MototaxistaPlanosRoute: MototaxistaPlanosRoute,
  PassageiroCarteiraRoute: PassageiroCarteiraRoute,
  PassageiroCorridasRoute: PassageiroCorridasRoute,
  PassageiroHomeRoute: PassageiroHomeRoute,
  PassageiroPerfilRoute: PassageiroPerfilRoute,
  FoodIndexRoute: FoodIndexRoute,
  MototaxistaIndexRoute: MototaxistaIndexRoute,
  PassageiroIndexRoute: PassageiroIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
