/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as MototaxiRouteImport } from './routes/mototaxi'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CidadeRouteImport } from './routes/cidade'
import { Route as AdministradorRouteImport } from './routes/administrador'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmRouteImport } from './routes/adm'
import { Route as AdmGateRouteImport } from './routes/_admGate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassageiroIndexRouteImport } from './routes/passageiro.index'
import { Route as MototaxistaIndexRouteImport } from './routes/mototaxista.index'
import { Route as CidadeIndexRouteImport } from './routes/cidade.index'
import { Route as PassageiroPerfilRouteImport } from './routes/passageiro.perfil'
import { Route as PassageiroHomeRouteImport } from './routes/passageiro.home'
import { Route as PassageiroCorridasRouteImport } from './routes/passageiro.corridas'
import { Route as PassageiroCarteiraRouteImport } from './routes/passageiro.carteira'
import { Route as MototaxistaPlanosRouteImport } from './routes/mototaxista.planos'
import { Route as MototaxistaPagamentoRouteImport } from './routes/mototaxista.pagamento'
import { Route as MototaxistaHomeRouteImport } from './routes/mototaxista.home'
import { Route as MototaxistaFotoRouteImport } from './routes/mototaxista.foto'
import { Route as MototaxistaDocumentosRouteImport } from './routes/mototaxista.documentos'
import { Route as MototaxistaCadastroRouteImport } from './routes/mototaxista.cadastro'
import { Route as MototaxistaAuthRouteImport } from './routes/mototaxista.auth'
import { Route as MototaxistaAguardandoRouteImport } from './routes/mototaxista.aguardando'
import { Route as CadastroPassageiroRouteImport } from './routes/cadastro.passageiro'
import { Route as AuthPassageiroRouteImport } from './routes/auth.passageiro'
import { Route as AuthMototaxistaRouteImport } from './routes/auth.mototaxista'
import { Route as AppPassageiroRouteImport } from './routes/app.passageiro'
import { Route as AppMototaxiRouteImport } from './routes/app.mototaxi'
import { Route as AppAdministradorRouteImport } from './routes/app.administrador'
import { Route as AdmSuspensoRouteImport } from './routes/adm.suspenso'
import { Route as AdmNegadoRouteImport } from './routes/adm.negado'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AdmGateAdmPrecosRouteImport } from './routes/_admGate.adm.precos'
import { Route as AdmGateAdmPainelRouteImport } from './routes/_admGate.adm.painel'
import { Route as AdmGateAdmGestaoRouteImport } from './routes/_admGate.adm.gestao'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxiRoute = MototaxiRouteImport.update({
  id: '/mototaxi',
  path: '/mototaxi',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadeRoute = CidadeRouteImport.update({
  id: '/cidade',
  path: '/cidade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministradorRoute = AdministradorRouteImport.update({
  id: '/administrador',
  path: '/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmRoute = AdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmGateRoute = AdmGateRouteImport.update({
  id: '/_admGate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroIndexRoute = PassageiroIndexRouteImport.update({
  id: '/passageiro/',
  path: '/passageiro/',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaIndexRoute = MototaxistaIndexRouteImport.update({
  id: '/mototaxista/',
  path: '/mototaxista/',
  getParentRoute: () => rootRouteImport,
} as any)
const CidadeIndexRoute = CidadeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CidadeRoute,
} as any)
const PassageiroPerfilRoute = PassageiroPerfilRouteImport.update({
  id: '/passageiro/perfil',
  path: '/passageiro/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroHomeRoute = PassageiroHomeRouteImport.update({
  id: '/passageiro/home',
  path: '/passageiro/home',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroCorridasRoute = PassageiroCorridasRouteImport.update({
  id: '/passageiro/corridas',
  path: '/passageiro/corridas',
  getParentRoute: () => rootRouteImport,
} as any)
const PassageiroCarteiraRoute = PassageiroCarteiraRouteImport.update({
  id: '/passageiro/carteira',
  path: '/passageiro/carteira',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaPlanosRoute = MototaxistaPlanosRouteImport.update({
  id: '/mototaxista/planos',
  path: '/mototaxista/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaPagamentoRoute = MototaxistaPagamentoRouteImport.update({
  id: '/mototaxista/pagamento',
  path: '/mototaxista/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaHomeRoute = MototaxistaHomeRouteImport.update({
  id: '/mototaxista/home',
  path: '/mototaxista/home',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaFotoRoute = MototaxistaFotoRouteImport.update({
  id: '/mototaxista/foto',
  path: '/mototaxista/foto',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaDocumentosRoute = MototaxistaDocumentosRouteImport.update({
  id: '/mototaxista/documentos',
  path: '/mototaxista/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaCadastroRoute = MototaxistaCadastroRouteImport.update({
  id: '/mototaxista/cadastro',
  path: '/mototaxista/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaAuthRoute = MototaxistaAuthRouteImport.update({
  id: '/mototaxista/auth',
  path: '/mototaxista/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MototaxistaAguardandoRoute = MototaxistaAguardandoRouteImport.update({
  id: '/mototaxista/aguardando',
  path: '/mototaxista/aguardando',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroPassageiroRoute = CadastroPassageiroRouteImport.update({
  id: '/cadastro/passageiro',
  path: '/cadastro/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPassageiroRoute = AuthPassageiroRouteImport.update({
  id: '/auth/passageiro',
  path: '/auth/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMototaxistaRoute = AuthMototaxistaRouteImport.update({
  id: '/auth/mototaxista',
  path: '/auth/mototaxista',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPassageiroRoute = AppPassageiroRouteImport.update({
  id: '/app/passageiro',
  path: '/app/passageiro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMototaxiRoute = AppMototaxiRouteImport.update({
  id: '/app/mototaxi',
  path: '/app/mototaxi',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdministradorRoute = AppAdministradorRouteImport.update({
  id: '/app/administrador',
  path: '/app/administrador',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmSuspensoRoute = AdmSuspensoRouteImport.update({
  id: '/suspenso',
  path: '/suspenso',
  getParentRoute: () => AdmRoute,
} as any)
const AdmNegadoRoute = AdmNegadoRouteImport.update({
  id: '/negado',
  path: '/negado',
  getParentRoute: () => AdmRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmGateAdmPrecosRoute = AdmGateAdmPrecosRouteImport.update({
  id: '/adm/precos',
  path: '/adm/precos',
  getParentRoute: () => AdmGateRoute,
} as any)
const AdmGateAdmPainelRoute = AdmGateAdmPainelRouteImport.update({
  id: '/adm/painel',
  path: '/adm/painel',
  getParentRoute: () => AdmGateRoute,
} as any)
const AdmGateAdmGestaoRoute = AdmGateAdmGestaoRouteImport.update({
  id: '/adm/gestao',
  path: '/adm/gestao',
  getParentRoute: () => AdmGateRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRouteWithChildren
  '/admin': typeof AdminRoute
  '/administrador': typeof AdministradorRoute
  '/cidade': typeof CidadeRouteWithChildren
  '/mcp': typeof McpRoute
  '/mototaxi': typeof MototaxiRoute
  '/privacidade': typeof PrivacidadeRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/adm/negado': typeof AdmNegadoRoute
  '/adm/suspenso': typeof AdmSuspensoRoute
  '/app/administrador': typeof AppAdministradorRoute
  '/app/mototaxi': typeof AppMototaxiRoute
  '/app/passageiro': typeof AppPassageiroRoute
  '/auth/mototaxista': typeof AuthMototaxistaRoute
  '/auth/passageiro': typeof AuthPassageiroRoute
  '/cadastro/passageiro': typeof CadastroPassageiroRoute
  '/mototaxista/aguardando': typeof MototaxistaAguardandoRoute
  '/mototaxista/auth': typeof MototaxistaAuthRoute
  '/mototaxista/cadastro': typeof MototaxistaCadastroRoute
  '/mototaxista/documentos': typeof MototaxistaDocumentosRoute
  '/mototaxista/foto': typeof MototaxistaFotoRoute
  '/mototaxista/home': typeof MototaxistaHomeRoute
  '/mototaxista/pagamento': typeof MototaxistaPagamentoRoute
  '/mototaxista/planos': typeof MototaxistaPlanosRoute
  '/passageiro/carteira': typeof PassageiroCarteiraRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/home': typeof PassageiroHomeRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/cidade/': typeof CidadeIndexRoute
  '/mototaxista/': typeof MototaxistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/adm/gestao': typeof AdmGateAdmGestaoRoute
  '/adm/painel': typeof AdmGateAdmPainelRoute
  '/adm/precos': typeof AdmGateAdmPrecosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm': typeof AdmRouteWithChildren
  '/admin': typeof AdminRoute
  '/administrador': typeof AdministradorRoute
  '/mcp': typeof McpRoute
  '/mototaxi': typeof MototaxiRoute
  '/privacidade': typeof PrivacidadeRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/adm/negado': typeof AdmNegadoRoute
  '/adm/suspenso': typeof AdmSuspensoRoute
  '/app/administrador': typeof AppAdministradorRoute
  '/app/mototaxi': typeof AppMototaxiRoute
  '/app/passageiro': typeof AppPassageiroRoute
  '/auth/mototaxista': typeof AuthMototaxistaRoute
  '/auth/passageiro': typeof AuthPassageiroRoute
  '/cadastro/passageiro': typeof CadastroPassageiroRoute
  '/mototaxista/aguardando': typeof MototaxistaAguardandoRoute
  '/mototaxista/auth': typeof MototaxistaAuthRoute
  '/mototaxista/cadastro': typeof MototaxistaCadastroRoute
  '/mototaxista/documentos': typeof MototaxistaDocumentosRoute
  '/mototaxista/foto': typeof MototaxistaFotoRoute
  '/mototaxista/home': typeof MototaxistaHomeRoute
  '/mototaxista/pagamento': typeof MototaxistaPagamentoRoute
  '/mototaxista/planos': typeof MototaxistaPlanosRoute
  '/passageiro/carteira': typeof PassageiroCarteiraRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/home': typeof PassageiroHomeRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/cidade': typeof CidadeIndexRoute
  '/mototaxista': typeof MototaxistaIndexRoute
  '/passageiro': typeof PassageiroIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/adm/gestao': typeof AdmGateAdmGestaoRoute
  '/adm/painel': typeof AdmGateAdmPainelRoute
  '/adm/precos': typeof AdmGateAdmPrecosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admGate': typeof AdmGateRouteWithChildren
  '/adm': typeof AdmRouteWithChildren
  '/admin': typeof AdminRoute
  '/administrador': typeof AdministradorRoute
  '/cidade': typeof CidadeRouteWithChildren
  '/mcp': typeof McpRoute
  '/mototaxi': typeof MototaxiRoute
  '/privacidade': typeof PrivacidadeRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/adm/negado': typeof AdmNegadoRoute
  '/adm/suspenso': typeof AdmSuspensoRoute
  '/app/administrador': typeof AppAdministradorRoute
  '/app/mototaxi': typeof AppMototaxiRoute
  '/app/passageiro': typeof AppPassageiroRoute
  '/auth/mototaxista': typeof AuthMototaxistaRoute
  '/auth/passageiro': typeof AuthPassageiroRoute
  '/cadastro/passageiro': typeof CadastroPassageiroRoute
  '/mototaxista/aguardando': typeof MototaxistaAguardandoRoute
  '/mototaxista/auth': typeof MototaxistaAuthRoute
  '/mototaxista/cadastro': typeof MototaxistaCadastroRoute
  '/mototaxista/documentos': typeof MototaxistaDocumentosRoute
  '/mototaxista/foto': typeof MototaxistaFotoRoute
  '/mototaxista/home': typeof MototaxistaHomeRoute
  '/mototaxista/pagamento': typeof MototaxistaPagamentoRoute
  '/mototaxista/planos': typeof MototaxistaPlanosRoute
  '/passageiro/carteira': typeof PassageiroCarteiraRoute
  '/passageiro/corridas': typeof PassageiroCorridasRoute
  '/passageiro/home': typeof PassageiroHomeRoute
  '/passageiro/perfil': typeof PassageiroPerfilRoute
  '/cidade/': typeof CidadeIndexRoute
  '/mototaxista/': typeof MototaxistaIndexRoute
  '/passageiro/': typeof PassageiroIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_admGate/adm/gestao': typeof AdmGateAdmGestaoRoute
  '/_admGate/adm/painel': typeof AdmGateAdmPainelRoute
  '/_admGate/adm/precos': typeof AdmGateAdmPrecosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/admin'
    | '/administrador'
    | '/cidade'
    | '/mcp'
    | '/mototaxi'
    | '/privacidade'
    | '/splash'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/adm/negado'
    | '/adm/suspenso'
    | '/app/administrador'
    | '/app/mototaxi'
    | '/app/passageiro'
    | '/auth/mototaxista'
    | '/auth/passageiro'
    | '/cadastro/passageiro'
    | '/mototaxista/aguardando'
    | '/mototaxista/auth'
    | '/mototaxista/cadastro'
    | '/mototaxista/documentos'
    | '/mototaxista/foto'
    | '/mototaxista/home'
    | '/mototaxista/pagamento'
    | '/mototaxista/planos'
    | '/passageiro/carteira'
    | '/passageiro/corridas'
    | '/passageiro/home'
    | '/passageiro/perfil'
    | '/cidade/'
    | '/mototaxista/'
    | '/passageiro/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/adm/gestao'
    | '/adm/painel'
    | '/adm/precos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm'
    | '/admin'
    | '/administrador'
    | '/mcp'
    | '/mototaxi'
    | '/privacidade'
    | '/splash'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/adm/negado'
    | '/adm/suspenso'
    | '/app/administrador'
    | '/app/mototaxi'
    | '/app/passageiro'
    | '/auth/mototaxista'
    | '/auth/passageiro'
    | '/cadastro/passageiro'
    | '/mototaxista/aguardando'
    | '/mototaxista/auth'
    | '/mototaxista/cadastro'
    | '/mototaxista/documentos'
    | '/mototaxista/foto'
    | '/mototaxista/home'
    | '/mototaxista/pagamento'
    | '/mototaxista/planos'
    | '/passageiro/carteira'
    | '/passageiro/corridas'
    | '/passageiro/home'
    | '/passageiro/perfil'
    | '/cidade'
    | '/mototaxista'
    | '/passageiro'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/adm/gestao'
    | '/adm/painel'
    | '/adm/precos'
  id:
    | '__root__'
    | '/'
    | '/_admGate'
    | '/adm'
    | '/admin'
    | '/administrador'
    | '/cidade'
    | '/mcp'
    | '/mototaxi'
    | '/privacidade'
    | '/splash'
    | '/termos'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/adm/negado'
    | '/adm/suspenso'
    | '/app/administrador'
    | '/app/mototaxi'
    | '/app/passageiro'
    | '/auth/mototaxista'
    | '/auth/passageiro'
    | '/cadastro/passageiro'
    | '/mototaxista/aguardando'
    | '/mototaxista/auth'
    | '/mototaxista/cadastro'
    | '/mototaxista/documentos'
    | '/mototaxista/foto'
    | '/mototaxista/home'
    | '/mototaxista/pagamento'
    | '/mototaxista/planos'
    | '/passageiro/carteira'
    | '/passageiro/corridas'
    | '/passageiro/home'
    | '/passageiro/perfil'
    | '/cidade/'
    | '/mototaxista/'
    | '/passageiro/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_admGate/adm/gestao'
    | '/_admGate/adm/painel'
    | '/_admGate/adm/precos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmGateRoute: typeof AdmGateRouteWithChildren
  AdmRoute: typeof AdmRouteWithChildren
  AdminRoute: typeof AdminRoute
  AdministradorRoute: typeof AdministradorRoute
  CidadeRoute: typeof CidadeRouteWithChildren
  McpRoute: typeof McpRoute
  MototaxiRoute: typeof MototaxiRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SplashRoute: typeof SplashRoute
  TermosRoute: typeof TermosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AppAdministradorRoute: typeof AppAdministradorRoute
  AppMototaxiRoute: typeof AppMototaxiRoute
  AppPassageiroRoute: typeof AppPassageiroRoute
  AuthMototaxistaRoute: typeof AuthMototaxistaRoute
  AuthPassageiroRoute: typeof AuthPassageiroRoute
  CadastroPassageiroRoute: typeof CadastroPassageiroRoute
  MototaxistaAguardandoRoute: typeof MototaxistaAguardandoRoute
  MototaxistaAuthRoute: typeof MototaxistaAuthRoute
  MototaxistaCadastroRoute: typeof MototaxistaCadastroRoute
  MototaxistaDocumentosRoute: typeof MototaxistaDocumentosRoute
  MototaxistaFotoRoute: typeof MototaxistaFotoRoute
  MototaxistaHomeRoute: typeof MototaxistaHomeRoute
  MototaxistaPagamentoRoute: typeof MototaxistaPagamentoRoute
  MototaxistaPlanosRoute: typeof MototaxistaPlanosRoute
  PassageiroCarteiraRoute: typeof PassageiroCarteiraRoute
  PassageiroCorridasRoute: typeof PassageiroCorridasRoute
  PassageiroHomeRoute: typeof PassageiroHomeRoute
  PassageiroPerfilRoute: typeof PassageiroPerfilRoute
  MototaxistaIndexRoute: typeof MototaxistaIndexRoute
  PassageiroIndexRoute: typeof PassageiroIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxi': {
      id: '/mototaxi'
      path: '/mototaxi'
      fullPath: '/mototaxi'
      preLoaderRoute: typeof MototaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidade': {
      id: '/cidade'
      path: '/cidade'
      fullPath: '/cidade'
      preLoaderRoute: typeof CidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrador': {
      id: '/administrador'
      path: '/administrador'
      fullPath: '/administrador'
      preLoaderRoute: typeof AdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm': {
      id: '/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admGate': {
      id: '/_admGate'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdmGateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/': {
      id: '/passageiro/'
      path: '/passageiro'
      fullPath: '/passageiro/'
      preLoaderRoute: typeof PassageiroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/': {
      id: '/mototaxista/'
      path: '/mototaxista'
      fullPath: '/mototaxista/'
      preLoaderRoute: typeof MototaxistaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cidade/': {
      id: '/cidade/'
      path: '/'
      fullPath: '/cidade/'
      preLoaderRoute: typeof CidadeIndexRouteImport
      parentRoute: typeof CidadeRoute
    }
    '/passageiro/perfil': {
      id: '/passageiro/perfil'
      path: '/passageiro/perfil'
      fullPath: '/passageiro/perfil'
      preLoaderRoute: typeof PassageiroPerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/home': {
      id: '/passageiro/home'
      path: '/passageiro/home'
      fullPath: '/passageiro/home'
      preLoaderRoute: typeof PassageiroHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/corridas': {
      id: '/passageiro/corridas'
      path: '/passageiro/corridas'
      fullPath: '/passageiro/corridas'
      preLoaderRoute: typeof PassageiroCorridasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passageiro/carteira': {
      id: '/passageiro/carteira'
      path: '/passageiro/carteira'
      fullPath: '/passageiro/carteira'
      preLoaderRoute: typeof PassageiroCarteiraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/planos': {
      id: '/mototaxista/planos'
      path: '/mototaxista/planos'
      fullPath: '/mototaxista/planos'
      preLoaderRoute: typeof MototaxistaPlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/pagamento': {
      id: '/mototaxista/pagamento'
      path: '/mototaxista/pagamento'
      fullPath: '/mototaxista/pagamento'
      preLoaderRoute: typeof MototaxistaPagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/home': {
      id: '/mototaxista/home'
      path: '/mototaxista/home'
      fullPath: '/mototaxista/home'
      preLoaderRoute: typeof MototaxistaHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/foto': {
      id: '/mototaxista/foto'
      path: '/mototaxista/foto'
      fullPath: '/mototaxista/foto'
      preLoaderRoute: typeof MototaxistaFotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/documentos': {
      id: '/mototaxista/documentos'
      path: '/mototaxista/documentos'
      fullPath: '/mototaxista/documentos'
      preLoaderRoute: typeof MototaxistaDocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/cadastro': {
      id: '/mototaxista/cadastro'
      path: '/mototaxista/cadastro'
      fullPath: '/mototaxista/cadastro'
      preLoaderRoute: typeof MototaxistaCadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/auth': {
      id: '/mototaxista/auth'
      path: '/mototaxista/auth'
      fullPath: '/mototaxista/auth'
      preLoaderRoute: typeof MototaxistaAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mototaxista/aguardando': {
      id: '/mototaxista/aguardando'
      path: '/mototaxista/aguardando'
      fullPath: '/mototaxista/aguardando'
      preLoaderRoute: typeof MototaxistaAguardandoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/passageiro': {
      id: '/cadastro/passageiro'
      path: '/cadastro/passageiro'
      fullPath: '/cadastro/passageiro'
      preLoaderRoute: typeof CadastroPassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/passageiro': {
      id: '/auth/passageiro'
      path: '/auth/passageiro'
      fullPath: '/auth/passageiro'
      preLoaderRoute: typeof AuthPassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/mototaxista': {
      id: '/auth/mototaxista'
      path: '/auth/mototaxista'
      fullPath: '/auth/mototaxista'
      preLoaderRoute: typeof AuthMototaxistaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/passageiro': {
      id: '/app/passageiro'
      path: '/app/passageiro'
      fullPath: '/app/passageiro'
      preLoaderRoute: typeof AppPassageiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/mototaxi': {
      id: '/app/mototaxi'
      path: '/app/mototaxi'
      fullPath: '/app/mototaxi'
      preLoaderRoute: typeof AppMototaxiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/administrador': {
      id: '/app/administrador'
      path: '/app/administrador'
      fullPath: '/app/administrador'
      preLoaderRoute: typeof AppAdministradorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm/suspenso': {
      id: '/adm/suspenso'
      path: '/suspenso'
      fullPath: '/adm/suspenso'
      preLoaderRoute: typeof AdmSuspensoRouteImport
      parentRoute: typeof AdmRoute
    }
    '/adm/negado': {
      id: '/adm/negado'
      path: '/negado'
      fullPath: '/adm/negado'
      preLoaderRoute: typeof AdmNegadoRouteImport
      parentRoute: typeof AdmRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admGate/adm/precos': {
      id: '/_admGate/adm/precos'
      path: '/adm/precos'
      fullPath: '/adm/precos'
      preLoaderRoute: typeof AdmGateAdmPrecosRouteImport
      parentRoute: typeof AdmGateRoute
    }
    '/_admGate/adm/painel': {
      id: '/_admGate/adm/painel'
      path: '/adm/painel'
      fullPath: '/adm/painel'
      preLoaderRoute: typeof AdmGateAdmPainelRouteImport
      parentRoute: typeof AdmGateRoute
    }
    '/_admGate/adm/gestao': {
      id: '/_admGate/adm/gestao'
      path: '/adm/gestao'
      fullPath: '/adm/gestao'
      preLoaderRoute: typeof AdmGateAdmGestaoRouteImport
      parentRoute: typeof AdmGateRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdmGateRouteChildren {
  AdmGateAdmGestaoRoute: typeof AdmGateAdmGestaoRoute
  AdmGateAdmPainelRoute: typeof AdmGateAdmPainelRoute
  AdmGateAdmPrecosRoute: typeof AdmGateAdmPrecosRoute
}

const AdmGateRouteChildren: AdmGateRouteChildren = {
  AdmGateAdmGestaoRoute: AdmGateAdmGestaoRoute,
  AdmGateAdmPainelRoute: AdmGateAdmPainelRoute,
  AdmGateAdmPrecosRoute: AdmGateAdmPrecosRoute,
}

const AdmGateRouteWithChildren =
  AdmGateRoute._addFileChildren(AdmGateRouteChildren)

interface AdmRouteChildren {
  AdmNegadoRoute: typeof AdmNegadoRoute
  AdmSuspensoRoute: typeof AdmSuspensoRoute
}

const AdmRouteChildren: AdmRouteChildren = {
  AdmNegadoRoute: AdmNegadoRoute,
  AdmSuspensoRoute: AdmSuspensoRoute,
}

const AdmRouteWithChildren = AdmRoute._addFileChildren(AdmRouteChildren)

interface CidadeRouteChildren {
  CidadeIndexRoute: typeof CidadeIndexRoute
}

const CidadeRouteChildren: CidadeRouteChildren = {
  CidadeIndexRoute: CidadeIndexRoute,
}

const CidadeRouteWithChildren =
  CidadeRoute._addFileChildren(CidadeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmGateRoute: AdmGateRouteWithChildren,
  AdmRoute: AdmRouteWithChildren,
  AdminRoute: AdminRoute,
  AdministradorRoute: AdministradorRoute,
  CidadeRoute: CidadeRouteWithChildren,
  McpRoute: McpRoute,
  MototaxiRoute: MototaxiRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SplashRoute: SplashRoute,
  TermosRoute: TermosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AppAdministradorRoute: AppAdministradorRoute,
  AppMototaxiRoute: AppMototaxiRoute,
  AppPassageiroRoute: AppPassageiroRoute,
  AuthMototaxistaRoute: AuthMototaxistaRoute,
  AuthPassageiroRoute: AuthPassageiroRoute,
  CadastroPassageiroRoute: CadastroPassageiroRoute,
  MototaxistaAguardandoRoute: MototaxistaAguardandoRoute,
  MototaxistaAuthRoute: MototaxistaAuthRoute,
  MototaxistaCadastroRoute: MototaxistaCadastroRoute,
  MototaxistaDocumentosRoute: MototaxistaDocumentosRoute,
  MototaxistaFotoRoute: MototaxistaFotoRoute,
  MototaxistaHomeRoute: MototaxistaHomeRoute,
  MototaxistaPagamentoRoute: MototaxistaPagamentoRoute,
  MototaxistaPlanosRoute: MototaxistaPlanosRoute,
  PassageiroCarteiraRoute: PassageiroCarteiraRoute,
  PassageiroCorridasRoute: PassageiroCorridasRoute,
  PassageiroHomeRoute: PassageiroHomeRoute,
  PassageiroPerfilRoute: PassageiroPerfilRoute,
  MototaxistaIndexRoute: MototaxistaIndexRoute,
  PassageiroIndexRoute: PassageiroIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
